Small changes
OvermindDL1/gradualixir pull request #2
Opened 2019-10-27 18:50 UTC by gomoripeti

2019-10-30 17:25 UTC, OvermindDL1 requested changes
Looks great!  Just one minor change unless it's a pun I'm missing?  ^.^;

2019-10-30 17:25 UTC, OvermindDL1 commented on lib/gradualixir.ex
> +  Examples speek for themselves
`s/speek/speak/`?  :-)

2019-10-30 23:05 UTC, gomoripeti commented on lib/gradualixir.ex
> +  Examples speek for themselves
no pun, this is a real plain typo

2019-10-30 23:17 UTC, OvermindDL1 commented
Looking great!  Any other changes or tests or so you want to add in or do you consider it good to merge?  :-)

2019-10-30 23:49 UTC, gomoripeti commented
that's all from me for now. I guess next time to bump gradualizer hash when the beta or first hex package comes out.
(I started to work on an Elixir formater earlier this year, but it's far from usable yet, unfortunately)

2019-10-31 14:28 UTC, OvermindDL1 commented
> (I started to work on an Elixir formater earlier this year, but it's far from usable yet, unfortunately)

It's easy enough to just call the built-in formatter, or PR changes to freedom_formatter, which is the formatter as a standalone project and some additional options.  :-)

2019-10-31 14:36 UTC, merged

2019-10-31 14:57 UTC, gomoripeti commented
The challenge is that Gradualizer works on the Erlang AST. Reconstructing types is mostly possible because they are mostly identically and eg Erlex can help here (except for the Gradualizer specific extensions). But reconstructing any expression from Erlang AST to Elixir quoted expr is probably impossible. (Eg was it a `with` expression or embedded `case` expressions) Maybe the way forward is not to print the whole problematic expressions just point to the line number.

2019-10-31 14:59 UTC, OvermindDL1 commented
Elixir projects by default include the debug chunk in the `*.beam` files so you can pull the original expression out of that (Elixir really doesn't like the debug chunk being removed as it uses it for a lot of error handling).  Types are identical though so that part is fine, just some reformatting and such of them.